# Generated by Django 4.0.2 on 2022-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.IntegerField()),
                ('error_type', models.CharField(max_length=100)),
                ('error_traceback', models.CharField(max_length=300)),
            ],
        ),
    ]
